image: jkozera/qt5-mingw32  # Dockerfile available at https://github.com/jkozera/docker-qt5-mingw32
script:
 - wine regedit /root/qttemp.reg  # doesn't work for some reason in Dockerfile's setup.sh
 - cd zeal
 - date +%Y%m%d > VERSION
 # a bit ugly version updating:
 - grep -v ZEAL_VERSION zeal.pro > zeal.pro.noversion
 - mv zeal.pro.noversion zeal.pro
 - echo 'DEFINES += ZEAL_VERSION=\\\"'`cat VERSION`'\\\"' >> zeal.pro
 - wine qmake
 - wine mingw32-make
 - mkdir zeal-$(cat VERSION)
 - cp release/zeal.exe zeal-$(cat VERSION)
 - cp -r icons zeal-$(cat VERSION)
 - wget https://bitbucket.org/jerzykozera/zeal-win32-binary-downloads/downloads/bsdtar.exe -O zeal-$(cat VERSION)/bsdtar.exe
 - wget https://bitbucket.org/jerzykozera/zeal-win32-binary-downloads/downloads/bzip2.dll -O zeal-$(cat VERSION)/bzip2.dll
 - wget https://bitbucket.org/jerzykozera/zeal-win32-binary-downloads/downloads/zlib1.dll -O zeal-$(cat VERSION)/zlib1.dll
 - mkdir zeal-$(cat VERSION)/imageformats
 - mkdir zeal-$(cat VERSION)/platforms
 - mkdir zeal-$(cat VERSION)/sqldrivers
 - cp /root/Tools/mingw482_32/opt/bin/ssleay32.dll zeal-$(cat VERSION)
 - cp /root/Tools/mingw482_32/opt/bin/libeay32.dll zeal-$(cat VERSION)
 - cp /root/5.3/mingw482_32/plugins/imageformats/qico.dll zeal-$(cat VERSION)/imageformats
 - cp /root/5.3/mingw482_32/plugins/platforms/qwindows.dll zeal-$(cat VERSION)/platforms
 - cp /root/5.3/mingw482_32/plugins/sqldrivers/qsqlite.dll zeal-$(cat VERSION)/sqldrivers
 - cp /root/5.3/mingw482_32/bin/libstdc++-6.dll zeal-$(cat VERSION)
 - cp /root/5.3/mingw482_32/bin/libgcc_s_dw2-1.dll zeal-$(cat VERSION)
 - cp /root/5.3/mingw482_32/bin/libwinpthread-1.dll zeal-$(cat VERSION)
 - cp /root/5.3/mingw482_32/bin/icu*.dll zeal-$(cat VERSION)
 - for l in Core Gui Multimedia MultimediaWidgets Network OpenGL Qml Quick Sql WebKit WebKitWidgets Widgets Xml Positioning PrintSupport Sensors; do cp /root/5.3/mingw482_32/bin/Qt5$l.dll zeal-$(cat VERSION); done
 - zip -r zeal-$(cat VERSION).zip zeal-$(cat VERSION)
 - mkdir win32_release
 - mv zeal-$(cat VERSION).zip win32_release

publish:
  github:
    branch: master
    artifacts:
     - win32_release/
    tag: $(cat VERSION)
    token: $$github_token
    user: jkozera
    repo: zeal
